### ISSUE TITLE
[feature] Improve display if no tomes are available

### ISSUE THREAD

**Issue by KCarretto** [spellshift/realm#234]
**Is your feature request related to a problem? Please describe.**
Currently when you load the createJob form, if no Tomes exist (or they cannot be fetched), there isn't any text displayed and the UI prevents you from continuing (it should).

![image](https://github.com/KCarretto/realm/assets/16250309/c9f70c1a-a184-42b7-92f8-9cff7674eb22)

**Describe the solution you'd like**
For newer users, we should make it a bit more clear that tomes need to be uploaded first, which can be done through a quick message in the UI.

**Describe alternatives you've considered**
None really.

**Additional context**
Nope.

**Comment by cmp5987** [comment]
We handle empty state for no matches but we need to handle 0 tomes found.
