### ISSUE TITLE
[bug] potential perf issues with "select agent sessions"

### ISSUE THREAD

**Issue by KCarretto** [spellshift/realm#235]
**Describe the bug**
When attempting to check a box to select a session, it can be quite delayed (e.g. takes a full second or two to mark as selected after clicking). This might be due to rendering a list of 900 sessions, perhaps we should limit how many are displayed at any given time to reduce perf issues.

**To Reproduce**
1. Run `ENABLE_TEST_DATA=1 go run ./tavern`
2. Run `cd tavern/internal/www && npm start`
3. Navigate through the createJob flow until it prompts you to "select agent sessions"
4. Attempt to check a box without performing any filters

**Expected behavior**
The box to feel responsive and mark itself as selected rather quickly.

**Screenshots**
![image](https://github.com/KCarretto/realm/assets/16250309/5d9a38a0-4a03-41ee-8b51-1520be955c94)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Google Chrome
 - Version: 114.0.5735.199 (Official Build) (64-bit) (cohort: Stable) 

**Additional context**
N/A

**Comment by cmp5987** [comment]
Can’t replicate recently. I think this was fixed.
