### ISSUE TITLE
[feature] Enforce Cargo Clippy

### ISSUE THREAD

**Issue by jabbate19** [spellshift/realm#253]
**Is your feature request related to a problem? Please describe.**
`cargo clippy` enforces good Rust code standards beyond `cargo fmt`. Enforcing this in Github Actions and in documentation would help keep code consistent for future development.

**Describe the solution you'd like**
Run `cargo clippy --fix` on all Rust projects, manually fixing anything that isn't automatically fixed.
Also, adding Github Actions to check for clippy compliance.

**Describe alternatives you've considered**
We could make our own formatting guide, but this is the Rust standard.

**Additional context**
N/A

**Comment by hulto** [comment]
I like the idea of having a standardized format.
I think the default does some things I think are less readable and would want to have configured like:
- function calls with multiple parameters getting broken into separate lines.
- trailing commas at least in multiline statements.

Definitely wanna look through the format during PR review in case there’s other readability concerns.

**Comment by Cictrone** [comment]
merged #510
