### ISSUE TITLE
Implement better names

### ISSUE THREAD

**Issue by hulto** [spellshift/realm#267]
**Is your feature request related to a problem? Please describe.**
Reading long beacon names is hard.

**Describe the solution you'd like**
Refactor beacon naming
1. Reduce number of adjactives from 2 to 1
2. Remove nouns with adjactives should be one word only
3. Remove numbers at the end.
4. Handle for uniqueness
     -  Graphql Unique constraint.
     - Try to add with a specific ID. If it fails retry with a new one until it succeeds or fails X times.

**Describe alternatives you've considered**
N/a

**Additional context**
N/a

**Comment by alexcote1** [comment]
https://github.com/KCarretto/realm/blob/dc64fc243a9e8ea00f8e89c412a4b891867c0619/tavern/internal/namegen/namegen.go#L891

**Comment by KCarretto** [comment]
This was fixed by @alexcote1 's PR
