### ISSUE TITLE
Make http callbacks proxy aware

### ISSUE THREAD

**Issue by hulto** [spellshift/realm#326]
**Is your feature request related to a problem? Please describe.**
Right now we don't have a way to perform communication out of a network when proxies are configured which is common at red v blue events and corp red team engagements.

**Describe the solution you'd like**
- Add a proxy check to the HTTP tavern executor.
- Add a test to verify that imix can tell when a proxy is configured on the system.
- Support Linux, Windows, and MacOS

**Describe alternatives you've considered**
Na

**Additional context**
Na

**Comment by hulto** [comment]
Could do it either:
- Every time we do a callback (would work if proxy is configured after the implant is deployed)
https://github.com/KCarretto/realm/blob/c22cee4dfb22dbb06695ede7829d13d3cba485f4/implants/lib/tavern/src/http.rs#L51C1-L59C1
- Or when the callback is defined (less system interaction) https://github.com/KCarretto/realm/blob/c22cee4dfb22dbb06695ede7829d13d3cba485f4/implants/lib/tavern/src/http.rs#L14

**Comment by jabbate19** [comment]
Are you trying to implement proxy into the agent, or find a way to know if a proxy is being used at the system level?

**Comment by hulto** [comment]
Both!
Nat CCDC runs a proxy for the event so we need a way to use it.
Ideally we'd automatically use it like how sliver does by pulling proxy info from the system.
