### ISSUE TITLE
Add a dead flag to the beacons field

### ISSUE THREAD

**Issue by hulto** [spellshift/realm#373]
**Is your feature request related to a problem? Please describe.**
In some situations you may want to manually flag beacons as dead.

**Describe the solution you'd like**
Add a field to the beacon (and maybe host?) ent that indicates if a beacon (or host) is dead. This should also be set automatically when the callback interval has elapsed.

**Describe alternatives you've considered**

**Additional context**

**Comment by KCarretto** [comment]
> This should also be set automatically when the callback interval has elapsed.

Either we manually set it or we automate / derive it, we can't do both

**Comment by KCarretto** [comment]
This is no longer wanted (CC @hulto )
