### ISSUE TITLE
Make the host-id file configurable

### ISSUE THREAD

**Issue by hulto** [spellshift/realm#399]
**Is your feature request related to a problem? Please describe.**
- Rn if you run imix as a low priv user on linux it will get a new host-id every time.
- This was also an issue with Windows.

**Describe the solution you'd like**
May be worth just making this configurable in the agent.
Adding a field to the JSON for `host-id file path`

**Describe alternatives you've considered**
Na

**Additional context**
Na

**Comment by jabbate19** [comment]
When you say `the JSON`, which JSON are you referencing? I'm guessing this was before we moved from imix config JSON to env vars, so how would you advise doing this in the new practice?

**Comment by hulto** [comment]
Yeah this was pre migration.
Let's make it a compile time ENV var with sensible defaults of world writable locations for Linux and Windows.

**Comment by hulto** [comment]
Resolved in #785
