### ISSUE TITLE
Build container doesn't install rustfmt

### ISSUE THREAD

**Issue by hulto** [spellshift/realm#409]
**Describe the bug**
The automatic code formatting that the dev container does requires `rustfmt`
This results in an error every time a rust file is saved.

```
[Error - 12:36:26 AM] Request textDocument/formatting failed.
  Message: rustfmt exited with:
                           Status: exit status: 1
                           stdout: 
                           stderr: error: 'rustfmt' is not installed for the toolchain 'nightly-2023-09-04-x86_64-unknown-linux-gnu'
To install, run `rustup component add rustfmt --toolchain nightly-2023-09-04-x86_64-unknown-linux-gnu`
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add the rustfmt component as a part of the dev container build.

**Comment by ankit-pn** [comment]
Hey I want to work on this issue, it would be great if anyone assign this to me. thanks

**Comment by hulto** [comment]
Awesome! Thanks @ankit-pn 🙂

**Comment by ankit-pn** [comment]
I am new to realm, can you please specify how to reproduce this error?

**Comment by hulto** [comment]
To reporoduce the error.
Clone the repo to your device system.
Open the project folder "realm" with VScode.

Once the projects open press Ctrl-P and search for "repo in dev container" if that option doesn't exist you'll have to install the dev containers extension in vscode.
Here's the VSCode docs just in case

https://code.visualstudio.com/docs/devcontainers/containers#_installation

VScode will take a while to build the dev container. Once the dev container finishes building navigate in the file explorer to realm > implants > imix > main.rs (or any rust file)
And press ctrl-S or File > save

This should trigger the autoformatting and raise the error as a pop up in the bottom left corner of VSCode.
If the files doesn't autoformat press ctrl-p and search for "format".
