### ISSUE TITLE
[feature] Add variable to show if task has output

### ISSUE THREAD

**Issue by cmp5987** [spellshift/realm#417]
**Is your feature request related to a problem? Please describe.**

Please add a boolean field for tracking if there is output for a task.

**Describe the solution you'd like**

Task field should now contain a hasOutput field that is a boolean true/false for if output is available. 

**Describe alternatives you've considered**

We have considered using timestamps to determine if output has been updated but found there are certain states where timestamps for lastModified is updated but output isn't guaranteed. Additionally, we currently are using 'output' field but would like to avoid making a request for potentially large blobs of data when this text will not be shown to users.

**Comment by KCarretto** [comment]
Same as #427
