### ISSUE TITLE
Add * support to the file list tome

### ISSUE THREAD

**Issue by hulto** [spellshift/realm#424]
**Is your feature request related to a problem? Please describe.**
I'd really like to do something like 
`file_list /home/*/` Right now that's not possible.

**Describe the solution you'd like**
Update the file_list tome to interpret the `*` character as a wild card.
Enumerate the files in the dir preceding it. If any are dirs queue them to be enumerated.

-or-
Update the file_list eldritch function to interpret `*` characters.

**Describe alternatives you've considered**

**Additional context**

**Comment by micahjmartin** [comment]
#575 allows you to set a recursion depth on file list. This would allow your use case of /home/*

I could add support for something like /etc/*open* which would loop through etc and match any files or folders with open in the name. Is this something you want?

**Comment by micahjmartin** [comment]
#575 has been updated to support globbing without recursion
