### ISSUE TITLE
Implement eldritch `file.follow` function

### ISSUE THREAD

**Issue by hulto** [spellshift/realm#461]
**Is your feature request related to a problem? Please describe.**
Being able to capture log data or bash_history files would be convenient.
Right now you'd have to read the whole file over and over. To avoid the problem of tracking new data and de-duping we could implement tail which will only collect new data.

**Describe the solution you'd like**
An Eldritch function `file.follow`
Which takes in:
- A file path
- A function (likely print)

The eldritch function should read from the specified file and call the function passed in whenever new data becomes available in the file.

**Describe alternatives you've considered**
Na

**Additional context**
Na

**Comment by jabbate19** [comment]
Would a more proper name for this be `file.feed`? When I think `file.tail` I think like `file.tail(filename, n)` which prints last n lines of file

**Comment by hulto** [comment]
Oooh good point.
maybe `file.follow` ?

**Comment by jabbate19** [comment]
That works with me.
