### ISSUE TITLE
Add arp_scan tome

### ISSUE THREAD

**Issue by hulto** [spellshift/realm#484]
**Is your feature request related to a problem? Please describe.**
We have an arp scan function but no tome to call it.

**Describe the solution you'd like**
Add a tome to call the arp_scan function and format the output.

**Describe alternatives you've considered**
Na

**Additional context**
Na

**Comment by micahjmartin** [comment]
@hulto `sys.get_ip()` does _not_ return the netmask but `pivot.arp_scan()` requires a netmask. Blocking until I can get netmask info

**Comment by hulto** [comment]
Ooh very fair.
