### ISSUE TITLE
Implement mkdir tome

### ISSUE THREAD

**Issue by hulto** [spellshift/realm#488]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Add tome to mkdir

**Describe alternatives you've considered**
Na

**Additional context**
Na

**Comment by KCarretto** [comment]
@hulto Can you describe a use case where all we want to do is make a directory? This seems too low level to be a tome.

**Comment by micahjmartin** [comment]
I feel like @KCarretto is correct, if we want a tome for authorized keys, it should go in there

**Comment by hulto** [comment]
Alright we'll wait till it becomes a strong ask / we have data to support the need.
