### ISSUE TITLE
Implement a get_net_info tome

### ISSUE THREAD

**Issue by hulto** [spellshift/realm#492]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Create a tome to return the current hosts ip info, hostname

**Describe alternatives you've considered**
Na

**Additional context**
Na

**Comment by KCarretto** [comment]
@hulto we already report this host information in imix callbacks directly

**Comment by hulto** [comment]
@KCarretto we only report primary IP if there's additional networks the host is connected to rn a get IP Tome is the only way to find that info.

**Comment by KCarretto** [comment]
> @KCarretto we only report primary IP if there's additional networks the host is connected to rn a get IP Tome is the only way to find that info.

Then maybe we could name this a bit more clearly, like `get_networks` or `get_net_info`
