### ISSUE TITLE
the codeblocks lib seems to render 

### ISSUE THREAD

**Issue by hulto** [spellshift/realm#507]
**Describe the bug**
Looks like the spaces in the codeblocks library are not consistent.
<img width="1455" alt="image" src="https://github.com/spellshift/realm/assets/7121375/41e99799-615d-470e-bfad-a5ec6d90b1b9">

If we can make them consistent that will make formatting in tomes much nicer.

Right tome output in tavern.
Left tome output copied into a terminal.
On the left we can see that their are the correct number of spaces are being used.

**Comment by cmp5987** [comment]
One day we may swap our code block component but this is all handled by a library currently. No plan to fix.
