### ISSUE TITLE
Kyle broke the UI - Platform name changed.

### ISSUE THREAD

**Issue by hulto** [spellshift/realm#514]
**Describe the bug**
#Blameless culture

<img width="676" alt="image" src="https://github.com/spellshift/realm/assets/7121375/6ebf1a89-8db6-4aaa-b8ca-fac91fe6e870">

Looks like the Platform ENUM changed recently.
The backend or frontend will need to update to align.

**Comment by cmp5987** [comment]
Frontend will match backend alignment since the formatting is based on GCP best practices. PR will be coming out this week
