### ISSUE TITLE
[feature] Add `exit()` or `quit()` function to eldritch

### ISSUE THREAD

**Issue by micahjmartin** [spellshift/realm#571]
There is no way to exit the REPL or stop execution of a script cleanly

**Describe the solution you'd like**
Add a `quit()` or `exit()` so scripts can exit

**Comment by KCarretto** [comment]
* For the REPL, ctrl + D should work.
* For a tome, you can just return from a function, for example:
```python
def main():
    if not file.exists("my dependency"):
        return
```

Does this resolve the issues you're experiencing?

**Comment by KCarretto** [comment]
Should be resolved via `eprint` and returning
