### ISSUE TITLE
Add hype links to header sections in docs

### ISSUE THREAD

**Issue by hulto** [spellshift/realm#656]
**Is your feature request related to a problem? Please describe.**
No easy way to link so a section in our docs.
Need to specify `-` instead of ` ` after the `#` slug eg.
https://docs.realm.pub/dev-guide/introduction#linear-history

**Describe the solution you'd like**
Add hyper links for each header to itself so users can right click copy link.

**Comment by KCarretto** [comment]
<img width="938" alt="image" src="https://github.com/spellshift/realm/assets/16250309/314c65e3-2617-49ca-95b7-d4a044e4973c">
This already exists?
